[project]
name = "vis-utils"
version = "0.1.0"

dependencies=[
    "imageio",
    "matplotlib",
    "open3d",
    "opencv-python",
    "scipy",
    "torch",
]

[tool.setuptools.packages.find]
include = ["vis_utils"]
